/*
 * This source file was generated by the Gradle 'init' task
 */
package ssh4p;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test
    void sanityCheck() {
        assertTrue(true);
    }
}
